{
	"expand":"names,schema",
	"startAt":0,
	"maxResults":50,
	"total":1,
	"issues":[
	          {
	        	  "expand":"operations,versionedRepresentations,editmeta,changelog,renderedFields",
	        	  "id":"23216",
	        	  "self":"https://logcop.atlassian.net/rest/api/2/issue/23216",
	        	  "key":"PACAF-563",
	        	  "fields":
	        	  {
	        		  "issuetype":{
	        			  "self":"https://logcop.atlassian.net/rest/api/2/issuetype/10002",
	        			  "id":"10002",
	        			  "description":"A task that needs to be done.",
	        			  "iconUrl":"https://logcop.atlassian.net/secure/viewavatar?size=xsmall&avatarId=10318&avatarType=issuetype",
	        			  "name":"Task",
	        			  "subtask":false,
	        			  "avatarId":10318
	        		  },
	        	  "timespent":21600,
	        	  "project":{
	        		  "self":"https://logcop.atlassian.net/rest/api/2/project/10005",
	        		  "id":"10005",
	        		  "key":"PACAF",
	        		  "name":"PACAF LOGCOP",
	        		  "avatarUrls":{
	        			  "48x48":"https://logcop.atlassian.net/secure/projectavatar?pid=10005&avatarId=10011",
	        			  "24x24":"https://logcop.atlassian.net/secure/projectavatar?size=small&pid=10005&avatarId=10011",
	        			  "16x16":"https://logcop.atlassian.net/secure/projectavatar?size=xsmall&pid=10005&avatarId=10011",
	        			  "32x32":"https://logcop.atlassian.net/secure/projectavatar?size=medium&pid=10005&avatarId=10011"}
	        	  },
	        	  "fixVersions":[],
	        	  "aggregatetimespent":21600,
	        	  "resolution":null,
	        	  "customfield_10500":null,
	        	  "resolutiondate":null,
	        	  "workratio":85,
	        	  "lastViewed":"2017-02-01T06:47:38.529-1000",
	        	  "watches":{
	        		  "self":"https://logcop.atlassian.net/rest/api/2/issue/PACAF-563/watchers",
	        		  "watchCount":1,
	        		  "isWatching":true
	        	  },
	        	  "created":"2017-01-31T09:02:03.000-1000",
	        	  "customfield_10021":7.0,
	        	  "priority":{
	        		  "self":"https://logcop.atlassian.net/rest/api/2/priority/3",
	        		  "iconUrl":"https://logcop.atlassian.net/images/icons/priorities/medium.svg",
	        		  "name":"Medium",
	        		  "id":"3"
	        	  },
	        	  "customfield_10024":[{
	        	                    	   "self":"https://logcop.atlassian.net/rest/api/2/customFieldOption/10007",
	        	                    	   "value":"Robert",
	        	                    	   "id":"10007"
	        	  }],
	        	  "customfield_10300":null,
	        	  "labels":[],
	        	  "customfield_10016":[
	        	                       "com.atlassian.greenhopper.service.sprint.Sprint@1a2645b[id=118,rapidViewId=6,state=ACTIVE,name=PACAF Sprint 21,goal=,startDate=2017-01-17T05:30:16.814-10:00,endDate=2017-02-02T05:30:00.000-10:00,completeDate=<null>,sequence=118]"
	        	  ],
                   "customfield_10017":"LET-1",
                   "timeestimate":3600,
                   "aggregatetimeoriginalestimate":25200,
                   "versions":[],
                   "issuelinks":[],
                   "assignee":{
                	   "self":"https://logcop.atlassian.net/rest/api/2/user?username=pacaf.logcop",
                	   "name":"pacaf.logcop","key":"peter.justeson.ctr",
                	   "emailAddress":"charles.e.emmons.ctr@navy.mil",
                	   "avatarUrls":{
                		   "48x48":"https://avatar-cdn.atlassian.com/a132434560003cfd8aeced57607ea664?s=48&d=https%3A%2F%2Flogcop.atlassian.net%2Fsecure%2Fuseravatar%3FavatarId%3D10334%26noRedirect%3Dtrue",
                		   "24x24":"https://avatar-cdn.atlassian.com/a132434560003cfd8aeced57607ea664?s=24&d=https%3A%2F%2Flogcop.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dsmall%26avatarId%3D10334%26noRedirect%3Dtrue",
                		   "16x16":"https://avatar-cdn.atlassian.com/a132434560003cfd8aeced57607ea664?s=16&d=https%3A%2F%2Flogcop.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dxsmall%26avatarId%3D10334%26noRedirect%3Dtrue",
                		   "32x32":"https://avatar-cdn.atlassian.com/a132434560003cfd8aeced57607ea664?s=32&d=https%3A%2F%2Flogcop.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dmedium%26avatarId%3D10334%26noRedirect%3Dtrue"
                	   },
                	   "displayName":"PACAF LOGCOP",
                	   "active":true,
                	   "timeZone":"Pacific/Honolulu"
                   },
                   "updated":"2017-02-01T06:47:38.000-1000",
                   "status":{
                	   "self":"https://logcop.atlassian.net/rest/api/2/status/3",
                	   "description":"This issue is being actively worked on at the moment by the assignee.",
                	   "iconUrl":"https://logcop.atlassian.net/images/icons/statuses/inprogress.png",
                	   "name":"In Progress",
                	   "id":"3",
                	   "statusCategory":{
                		   "self":"https://logcop.atlassian.net/rest/api/2/statuscategory/4",
                		   "id":4,
                		   "key":"indeterminate",
                		   "colorName":"yellow",
                		   "name":"In Progress"
                	   }
                   },
                   "components":[],
                   "timeoriginalestimate":25200,
                   "description":"Includes getting cbt to work without meeting_fk in schedule settings table. That is being replaced by a join table so other modules that need recurrence can all use the same table.",
                   "customfield_10010":null,
                   "customfield_10011":null,
                   "customfield_10012":null,
                   "customfield_10013":"Not started",
                   "customfield_10015":"0|i00l9b:",
                   "customfield_10005":null,
                   "customfield_10006":null,
                   "customfield_10600":null,
                   "customfield_10007":null,
                   "customfield_10008":null,
                   "customfield_10009":null,
                   "aggregatetimeestimate":3600,
                   "summary":"CBT - Finish removing meeting id from schedule settings",
                   "creator":{
                	   "self":"https://logcop.atlassian.net/rest/api/2/user?username=pacaf.logcop",
                	   "name":"pacaf.logcop",
                	   "key":"peter.justeson.ctr",
                	   "emailAddress":"charles.e.emmons.ctr@navy.mil",
                	   "avatarUrls":{
                		   "48x48":"https://avatar-cdn.atlassian.com/a132434560003cfd8aeced57607ea664?s=48&d=https%3A%2F%2Flogcop.atlassian.net%2Fsecure%2Fuseravatar%3FavatarId%3D10334%26noRedirect%3Dtrue",
                		   "24x24":"https://avatar-cdn.atlassian.com/a132434560003cfd8aeced57607ea664?s=24&d=https%3A%2F%2Flogcop.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dsmall%26avatarId%3D10334%26noRedirect%3Dtrue",
                		   "16x16":"https://avatar-cdn.atlassian.com/a132434560003cfd8aeced57607ea664?s=16&d=https%3A%2F%2Flogcop.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dxsmall%26avatarId%3D10334%26noRedirect%3Dtrue",
                		   "32x32":"https://avatar-cdn.atlassian.com/a132434560003cfd8aeced57607ea664?s=32&d=https%3A%2F%2Flogcop.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dmedium%26avatarId%3D10334%26noRedirect%3Dtrue"
                	   },
                	   "displayName":"PACAF LOGCOP",
                	   "active":true,
                	   "timeZone":"Pacific/Honolulu"
                   },
                   "subtasks":[],
                   "reporter":{
                	   "self":"https://logcop.atlassian.net/rest/api/2/user?username=pacaf.logcop",
                	   "name":"pacaf.logcop",
                	   "key":"peter.justeson.ctr",
                	   "emailAddress":"charles.e.emmons.ctr@navy.mil",
                	   "avatarUrls":{
                		   "48x48":"https://avatar-cdn.atlassian.com/a132434560003cfd8aeced57607ea664?s=48&d=https%3A%2F%2Flogcop.atlassian.net%2Fsecure%2Fuseravatar%3FavatarId%3D10334%26noRedirect%3Dtrue",
                		   "24x24":"https://avatar-cdn.atlassian.com/a132434560003cfd8aeced57607ea664?s=24&d=https%3A%2F%2Flogcop.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dsmall%26avatarId%3D10334%26noRedirect%3Dtrue",
                		   "16x16":"https://avatar-cdn.atlassian.com/a132434560003cfd8aeced57607ea664?s=16&d=https%3A%2F%2Flogcop.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dxsmall%26avatarId%3D10334%26noRedirect%3Dtrue",
                		   "32x32":"https://avatar-cdn.atlassian.com/a132434560003cfd8aeced57607ea664?s=32&d=https%3A%2F%2Flogcop.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dmedium%26avatarId%3D10334%26noRedirect%3Dtrue"
                		},
                		"displayName":"PACAF LOGCOP",
                		"active":true,
                		"timeZone":"Pacific/Honolulu"
                  },
                  "customfield_10000":null,
                  "aggregateprogress":{
                	  "progress":21600,
                	  "total":25200,
                	  "percent":85
                  },
                  "customfield_10001":null,
                  "customfield_10200":null,
                  "customfield_10400":"{}",
                  "customfield_10004":null,
                  "environment":null,
                  "duedate":null,
                  "progress":{
                	  "progress":21600,
                	  "total":25200,
                	  "percent":85
                  },
                  "votes":{
                	  "self":"https://logcop.atlassian.net/rest/api/2/issue/PACAF-563/votes",
                	  "votes":0,
                	  "hasVoted":false
                  }
                }
	      }]
}
